---
title: "tree maps, area charts, and stacked area charts  "
output: html_notebook
---


```{r}
# setting current working diirectory
setwd("/Users/madhukarayachit/DSC640")
```

```{r}
#Load in libraries

#Load libraries
library(readxl)
library(ggplot2)
library(tidyverse)
library(plotly)
library(dbplyr)
library(scales)
library(plotly)
library(maps)
```


```{r}
# load data


costco <- read.csv("Data/ex5-2/costcos-geocoded.csv")
ppg <- read.csv("Data/ex5-2/ppg2008.csv")

nba
costco

```

## Heat map 
```{r}
nba_matrix <- data.matrix(nba)
nba_heatmap <- heatmap(nba_matrix, Rowv=NA, Colv=NA, col = heat.colors(256), scale="column", margins=c(5,10))

```
## Spatial chart

```{r}
#Close up of states
map(database = 'state', col = '#cccccc')
symbols(costco$Longitude, costco$Latitude, bg = '#e2373f', fg = '#ffffff',
        lwd = 0.5, circles = rep(1, length(costco$Longitude)), 
        inches = 0.05, add = TRUE)

#View with Hawaii and Alaska included
map(database = 'world', col = '#cccccc')
symbols(costco$Longitude, costco$Latitude, bg = '#e2373f', fg = '#ffffff',
        lwd = 0.5, circles = rep(1, length(costco$Longitude)), 
                      inches = 0.05, add = TRUE)
```

## Contour plot
```{r}
#Using ggplot

ggplot(nba, aes(x=FTM, y=FTA))+
  theme_bw()+
  geom_point(alpha=0.1, col='red')+
  geom_density2d(color='black')+
  ggtitle('Contour Plot')+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(x='FTM', y='FTA')
```



